[firebase]
apiKey = "AIzaSyBi-y0EX__aAO0u1wrEf5-dvkVWIxGdHPc"
authDomain = "fanflux-299ad.firebaseapp.com"
databaseURL = "https://fanflux-299ad-default-rtdb.firebaseio.com"
projectId = "fanflux-299ad"
storageBucket = "fanflux-299ad.appspot.com"
messagingSenderId = "643979891706"
appId = "1:643979891706:web:107a938bb3372ac3774c43"
measurementId = "G-1234567890"