[firebase]
apiKey = "AIzaSyBYd2Ijzl65U-0myjl6ElQ7hO5cGeDXAbM"
authDomain = "fanflux-299ad.firebaseapp.com"
databaseURL = "https://fanflux-299ad-default-rtdb.firebaseio.com"
projectId = "fanflux-299ad"
storageBucket = "fanflux-299ad.appspot.com"
messagingSenderId = "643979891706"
appId = "1:643979891706:web:107a938bb3372ac3774c43"
measurementId = "G-1234567890"

[email]
username = "darnel.m@distinctlymktg.com"
password = "wrkl qykt dvon eeyd"
