[firebase]
apiKey = "AIzaSyAyKYl5zvgHQrcNYRCH9eqnF9SkMYG2LE8"
authDomain = "fanflux-299ad.firebaseapp.com"
databaseURL = "https://fanflux-299ad-default-rtdb.firebaseio.com"
projectId = "fanflux-299ad"
storageBucket = "fanflux-299ad.appspot.com"
messagingSenderId = "643979891706"
appId = "1:643979891706:web:107a938bb3372ac3774c43"
measurementId = "G-1234567890"

[email]
username = "darnel.m@distinctlymktg.com"
password = "wrkl qykt dvon eeyd"

[credentials]
user1 = {name = "User One", password = "password1"}
user2 = {name = "User Two", password = "password2"}
user3 = {name = "User Three", password = "password3"}
user4 = {name = "User Four", password = "password4"}
user5 = {name = "User Five", password = "password5"}
user6 = {name = "User Six", password = "password6"}
user7 = {name = "User Seven", password = "password7"}
user8 = {name = "User Eight", password = "password8"}
user9 = {name = "User Nine", password = "password9"}
user10 = {name = "User Ten", password = "password10"}
user11 = {name = "User Eleven", password = "password11"}
user12 = {name = "User Twelve", password = "password12"}
user13 = {name = "User Thirteen", password = "password13"}
user14 = {name = "User Fourteen", password = "password14"}
user15 = {name = "User Fifteen", password = "password15"}
user16 = {name = "User Sixteen", password = "password16"}
user17 = {name = "User Seventeen", password = "password17"}
user18 = {name = "User Eighteen", password = "password18"}
user19 = {name = "User Nineteen", password = "password19"}
user20 = {name = "User Twenty", password = "password20"}
user21 = {name = "User Twenty One", password = "password21"}
user22 = {name = "User Twenty Two", password = "password22"}
user23 = {name = "User Twenty Three", password = "password23"}
user24 = {name = "User Twenty Four", password = "password24"}
user25 = {name = "User Twenty Five", password = "password25"}
user26 = {name = "User Twenty Six", password = "password26"}
user27 = {name = "User Twenty Seven", password = "password27"}
user28 = {name = "User Twenty Eight", password = "password28"}
user29 = {name = "User Twenty Nine", password = "password29"}
user30 = {name = "User Thirty", password = "password30"}
user31 = {name = "User Thirty One", password = "password31"}
user32 = {name = "User Thirty Two", password = "password32"}
user33 = {name = "User Thirty Three", password = "password33"}
user34 = {name = "User Thirty Four", password = "password34"}
user35 = {name = "User Thirty Five", password = "password35"}
user36 = {name = "User Thirty Six", password = "password36"}
user37 = {name = "User Thirty Seven", password = "password37"}
user38 = {name = "User Thirty Eight", password = "password38"}
user39 = {name = "User Thirty Nine", password = "password39"}
user40 = {name = "User Forty", password = "password40"}
user41 = {name = "User Forty One", password = "password41"}
user42 = {name = "User Forty Two", password = "password42"}
user43 = {name = "User Forty Three", password = "password43"}
user44 = {name = "User Forty Four", password = "password44"}
user45 = {name = "User Forty Five", password = "password45"}
user46 = {name = "User Forty Six", password = "password46"}
user47 = {name = "User Forty Seven", password = "password47"}
user48 = {name = "User Forty Eight", password = "password48"}
user49 = {name = "User Forty Nine", password = "password49"}
user50 = {name = "User Fifty", password = "password50"}
user51 = {name = "User Fifty One", password = "password51"}
user52 = {name = "User Fifty Two", password = "password52"}
user53 = {name = "User Fifty Three", password = "password53"}
user54 = {name = "User Fifty Four", password = "password54"}
user55 = {name = "User Fifty Five", password = "password55"}
user56 = {name = "User Fifty Six", password = "password56"}
user57 = {name = "User Fifty Seven", password = "password57"}
user58 = {name = "User Fifty Eight", password = "password58"}
user59 = {name = "User Fifty Nine", password = "password59"}
user60 = {name = "User Sixty", password = "password60"}

